version: "3"
services:
  valheim:
    build: .
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      NAME: ${NAME}
      WORLD: ${WORLD}
      PASSWORD: ${PASSWORD}
    volumes:
    - ${SAVES}:/saves